# Generated by Django 5.0.3 on 2024-04-03 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User1',
            new_name='User',
        ),
    ]
