# Generated by Django 4.2.11 on 2024-04-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_planner', '0002_rename_user1_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=1)),
            ],
        ),
    ]
