# Generated by Django 4.2.11 on 2024-05-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_planner', '0008_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
