# Generated by Django 4.2.11 on 2024-05-24 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_planner', '0009_alter_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 24, 7, 38, 4, 601506, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
